name: reusable workflow

on:
   workflow_call:
        inputs:
             username:
                    description: 'some name'
                    default: 'john-doe'
                    type: 'string'
                    required: false


jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
       - name: Print the input name to STDOUT
         run: echo The username is ${{ inputs.username }}
       - run: echo "reusable workflow "

